name: vpn_demo
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  animated_snack_bar: ^0.4.0
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.6
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  kdgaugeview: ^1.0.5
  local_auth: ^2.2.0
  lottie: ^3.1.0
  page_view_dot_indicator: ^2.3.0
  shared_preferences: ^2.2.3
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/drawerImgs/
    - assets/images/ob/
    - assets/images/settings/
    - assets/images/share/
    - assets/images/socials/
    - assets/images/about/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
